/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : string,
  'category' : string,
}
export interface ConsultationBooking {
  'id' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'clientId' : Principal,
  'requirementId' : [] | [string],
  'scheduledDate' : Time,
  'lawyerId' : Principal,
  'notes' : string,
}
export type ExternalBlob = Uint8Array;
export interface LawyerProfile {
  'bio' : string,
  'userId' : Principal,
  'yearsExperience' : bigint,
  'name' : string,
  'education' : string,
  'languages' : Array<string>,
  'averageRating' : number,
  'specialization' : string,
  'photo' : [] | [ExternalBlob],
  'totalReviews' : bigint,
  'consultationFee' : bigint,
  'location' : string,
  'verificationStatus' : { 'verified' : null } |
    { 'pending' : null } |
    { 'rejected' : null },
  'verificationDoc' : [] | [ExternalBlob],
}
export interface LegalRequirement {
  'id' : string,
  'status' : { 'closed' : null } |
    { 'assigned' : null } |
    { 'open' : null },
  'title' : string,
  'clientId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'legalCategory' : string,
  'location' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'read' : boolean,
  'receiverId' : Principal,
  'timestamp' : Time,
  'senderId' : Principal,
}
export interface Review {
  'id' : string,
  'clientId' : Principal,
  'createdAt' : Time,
  'lawyerId' : Principal,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : { 'client' : null } |
    { 'lawyer' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminVerifyLawyer' : ActorMethod<
    [Principal, { 'verified' : null } | { 'rejected' : null }],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookConsultation' : ActorMethod<[ConsultationBooking], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], undefined>,
  'createOrUpdateLawyerProfile' : ActorMethod<[LawyerProfile], undefined>,
  'filterLawyersByLocation' : ActorMethod<[string], Array<LawyerProfile>>,
  'filterLawyersBySpecialization' : ActorMethod<[string], Array<LawyerProfile>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal, Principal], Array<Message>>,
  'getLawyerById' : ActorMethod<[Principal], [] | [LawyerProfile]>,
  'getLawyerReviews' : ActorMethod<[Principal], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listLawyerBookings' : ActorMethod<[Principal], Array<ConsultationBooking>>,
  'listLawyers' : ActorMethod<[], Array<LawyerProfile>>,
  'listMyBookings' : ActorMethod<[Principal], Array<ConsultationBooking>>,
  'listMyConversations' : ActorMethod<[Principal], Array<Message>>,
  'listMyRequirements' : ActorMethod<[Principal], Array<LegalRequirement>>,
  'listOpenRequirements' : ActorMethod<[], Array<LegalRequirement>>,
  'postRequirement' : ActorMethod<[LegalRequirement], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Message], undefined>,
  'setRole' : ActorMethod<
    [{ 'client' : null } | { 'lawyer' : null }],
    undefined
  >,
  'submitReview' : ActorMethod<[Review], undefined>,
  'submitVerificationDoc' : ActorMethod<[Principal, ExternalBlob], undefined>,
  'updateBookingStatus' : ActorMethod<
    [
      string,
      { 'cancelled' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'updateRequirementStatus' : ActorMethod<
    [string, { 'closed' : null } | { 'assigned' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];