/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ConsultationBooking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'clientId' : IDL.Principal,
  'requirementId' : IDL.Opt(IDL.Text),
  'scheduledDate' : Time,
  'lawyerId' : IDL.Principal,
  'notes' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
  'category' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LawyerProfile = IDL.Record({
  'bio' : IDL.Text,
  'userId' : IDL.Principal,
  'yearsExperience' : IDL.Nat,
  'name' : IDL.Text,
  'education' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'averageRating' : IDL.Float64,
  'specialization' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'totalReviews' : IDL.Nat,
  'consultationFee' : IDL.Nat,
  'location' : IDL.Text,
  'verificationStatus' : IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'verificationDoc' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'client' : IDL.Null, 'lawyer' : IDL.Null }),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'receiverId' : IDL.Principal,
  'timestamp' : Time,
  'senderId' : IDL.Principal,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'clientId' : IDL.Principal,
  'createdAt' : Time,
  'lawyerId' : IDL.Principal,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const LegalRequirement = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'closed' : IDL.Null,
    'assigned' : IDL.Null,
    'open' : IDL.Null,
  }),
  'title' : IDL.Text,
  'clientId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'legalCategory' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminVerifyLawyer' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({ 'verified' : IDL.Null, 'rejected' : IDL.Null }),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookConsultation' : IDL.Func([ConsultationBooking], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [], []),
  'createOrUpdateLawyerProfile' : IDL.Func([LawyerProfile], [], []),
  'filterLawyersByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LawyerProfile)],
      ['query'],
    ),
  'filterLawyersBySpecialization' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LawyerProfile)],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getLawyerById' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(LawyerProfile)],
      ['query'],
    ),
  'getLawyerReviews' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listLawyerBookings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ConsultationBooking)],
      ['query'],
    ),
  'listLawyers' : IDL.Func([], [IDL.Vec(LawyerProfile)], ['query']),
  'listMyBookings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ConsultationBooking)],
      ['query'],
    ),
  'listMyConversations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'listMyRequirements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LegalRequirement)],
      ['query'],
    ),
  'listOpenRequirements' : IDL.Func([], [IDL.Vec(LegalRequirement)], ['query']),
  'postRequirement' : IDL.Func([LegalRequirement], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([Message], [], []),
  'setRole' : IDL.Func(
      [IDL.Variant({ 'client' : IDL.Null, 'lawyer' : IDL.Null })],
      [],
      [],
    ),
  'submitReview' : IDL.Func([Review], [], []),
  'submitVerificationDoc' : IDL.Func([IDL.Principal, ExternalBlob], [], []),
  'updateBookingStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateRequirementStatus' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'closed' : IDL.Null, 'assigned' : IDL.Null })],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ConsultationBooking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'clientId' : IDL.Principal,
    'requirementId' : IDL.Opt(IDL.Text),
    'scheduledDate' : Time,
    'lawyerId' : IDL.Principal,
    'notes' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LawyerProfile = IDL.Record({
    'bio' : IDL.Text,
    'userId' : IDL.Principal,
    'yearsExperience' : IDL.Nat,
    'name' : IDL.Text,
    'education' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'averageRating' : IDL.Float64,
    'specialization' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'totalReviews' : IDL.Nat,
    'consultationFee' : IDL.Nat,
    'location' : IDL.Text,
    'verificationStatus' : IDL.Variant({
      'verified' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'verificationDoc' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'client' : IDL.Null, 'lawyer' : IDL.Null }),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'receiverId' : IDL.Principal,
    'timestamp' : Time,
    'senderId' : IDL.Principal,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'clientId' : IDL.Principal,
    'createdAt' : Time,
    'lawyerId' : IDL.Principal,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const LegalRequirement = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'closed' : IDL.Null,
      'assigned' : IDL.Null,
      'open' : IDL.Null,
    }),
    'title' : IDL.Text,
    'clientId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'legalCategory' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminVerifyLawyer' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({ 'verified' : IDL.Null, 'rejected' : IDL.Null }),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookConsultation' : IDL.Func([ConsultationBooking], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [], []),
    'createOrUpdateLawyerProfile' : IDL.Func([LawyerProfile], [], []),
    'filterLawyersByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LawyerProfile)],
        ['query'],
      ),
    'filterLawyersBySpecialization' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LawyerProfile)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getLawyerById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(LawyerProfile)],
        ['query'],
      ),
    'getLawyerReviews' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listLawyerBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ConsultationBooking)],
        ['query'],
      ),
    'listLawyers' : IDL.Func([], [IDL.Vec(LawyerProfile)], ['query']),
    'listMyBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ConsultationBooking)],
        ['query'],
      ),
    'listMyConversations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'listMyRequirements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LegalRequirement)],
        ['query'],
      ),
    'listOpenRequirements' : IDL.Func(
        [],
        [IDL.Vec(LegalRequirement)],
        ['query'],
      ),
    'postRequirement' : IDL.Func([LegalRequirement], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([Message], [], []),
    'setRole' : IDL.Func(
        [IDL.Variant({ 'client' : IDL.Null, 'lawyer' : IDL.Null })],
        [],
        [],
      ),
    'submitReview' : IDL.Func([Review], [], []),
    'submitVerificationDoc' : IDL.Func([IDL.Principal, ExternalBlob], [], []),
    'updateBookingStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateRequirementStatus' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'closed' : IDL.Null, 'assigned' : IDL.Null })],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };