/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface LegalRequirement {
    id: string;
    status: Variant_closed_assigned_open;
    title: string;
    clientId: Principal;
    createdAt: Time;
    description: string;
    legalCategory: string;
    location: string;
}
export interface BlogPost {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    author: string;
    category: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Message {
    id: string;
    content: string;
    read: boolean;
    receiverId: Principal;
    timestamp: Time;
    senderId: Principal;
}
export interface ConsultationBooking {
    id: string;
    status: Variant_cancelled_pending_completed_confirmed;
    clientId: Principal;
    requirementId?: string;
    scheduledDate: Time;
    lawyerId: Principal;
    notes: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LawyerProfile {
    bio: string;
    userId: Principal;
    yearsExperience: bigint;
    name: string;
    education: string;
    languages: Array<string>;
    averageRating: number;
    specialization: string;
    photo?: ExternalBlob;
    totalReviews: bigint;
    consultationFee: bigint;
    location: string;
    verificationStatus: Variant_verified_pending_rejected;
    verificationDoc?: ExternalBlob;
}
export interface UserProfile {
    name: string;
    role: Variant_client_lawyer;
}
export interface Review {
    id: string;
    clientId: Principal;
    createdAt: Time;
    lawyerId: Principal;
    comment: string;
    rating: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_completed_confirmed {
    cancelled = "cancelled",
    completed = "completed",
    confirmed = "confirmed"
}
export enum Variant_cancelled_pending_completed_confirmed {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum Variant_client_lawyer {
    client = "client",
    lawyer = "lawyer"
}
export enum Variant_closed_assigned {
    closed = "closed",
    assigned = "assigned"
}
export enum Variant_closed_assigned_open {
    closed = "closed",
    assigned = "assigned",
    open = "open"
}
export enum Variant_verified_pending_rejected {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum Variant_verified_rejected {
    verified = "verified",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminVerifyLawyer(lawyerId: Principal, status: Variant_verified_rejected): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookConsultation(booking: ConsultationBooking): Promise<void>;
    createBlogPost(post: BlogPost): Promise<void>;
    createOrUpdateLawyerProfile(profile: LawyerProfile): Promise<void>;
    filterLawyersByLocation(location: string): Promise<Array<LawyerProfile>>;
    filterLawyersBySpecialization(specialization: string): Promise<Array<LawyerProfile>>;
    getBlogPost(postId: string): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(user1: Principal, user2: Principal): Promise<Array<Message>>;
    getLawyerById(lawyerId: Principal): Promise<LawyerProfile | null>;
    getLawyerReviews(lawyerId: Principal): Promise<Array<Review>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listBlogPosts(): Promise<Array<BlogPost>>;
    listLawyerBookings(lawyerId: Principal): Promise<Array<ConsultationBooking>>;
    listLawyers(): Promise<Array<LawyerProfile>>;
    listMyBookings(clientId: Principal): Promise<Array<ConsultationBooking>>;
    listMyConversations(userId: Principal): Promise<Array<Message>>;
    listMyRequirements(clientId: Principal): Promise<Array<LegalRequirement>>;
    listOpenRequirements(): Promise<Array<LegalRequirement>>;
    postRequirement(requirement: LegalRequirement): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(message: Message): Promise<void>;
    setRole(role: Variant_client_lawyer): Promise<void>;
    submitReview(review: Review): Promise<void>;
    submitVerificationDoc(lawyerId: Principal, doc: ExternalBlob): Promise<void>;
    updateBookingStatus(bookingId: string, status: Variant_cancelled_completed_confirmed): Promise<void>;
    updateRequirementStatus(requirementId: string, status: Variant_closed_assigned): Promise<void>;
}
import type { BlogPost as _BlogPost, ConsultationBooking as _ConsultationBooking, ExternalBlob as _ExternalBlob, LawyerProfile as _LawyerProfile, LegalRequirement as _LegalRequirement, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminVerifyLawyer(arg0: Principal, arg1: Variant_verified_rejected): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminVerifyLawyer(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminVerifyLawyer(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookConsultation(arg0: ConsultationBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookConsultation(to_candid_ConsultationBooking_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookConsultation(to_candid_ConsultationBooking_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0);
            return result;
        }
    }
    async createOrUpdateLawyerProfile(arg0: LawyerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateLawyerProfile(await to_candid_LawyerProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateLawyerProfile(await to_candid_LawyerProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async filterLawyersByLocation(arg0: string): Promise<Array<LawyerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterLawyersByLocation(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterLawyersByLocation(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterLawyersBySpecialization(arg0: string): Promise<Array<LawyerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterLawyersBySpecialization(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterLawyersBySpecialization(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal, arg1: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0, arg1);
            return result;
        }
    }
    async getLawyerById(arg0: Principal): Promise<LawyerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyerById(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyerById(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLawyerReviews(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyerReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyerReviews(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts();
            return result;
        }
    }
    async listLawyerBookings(arg0: Principal): Promise<Array<ConsultationBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLawyerBookings(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLawyerBookings(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLawyers(): Promise<Array<LawyerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLawyers();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLawyers();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyBookings(arg0: Principal): Promise<Array<ConsultationBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBookings(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBookings(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyConversations(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyConversations(arg0);
            return result;
        }
    }
    async listMyRequirements(arg0: Principal): Promise<Array<LegalRequirement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyRequirements(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyRequirements(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOpenRequirements(): Promise<Array<LegalRequirement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOpenRequirements();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOpenRequirements();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async postRequirement(arg0: LegalRequirement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postRequirement(to_candid_LegalRequirement_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postRequirement(to_candid_LegalRequirement_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async setRole(arg0: Variant_client_lawyer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRole(to_candid_variant_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRole(to_candid_variant_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async submitVerificationDoc(arg0: Principal, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVerificationDoc(arg0, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVerificationDoc(arg0, await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: Variant_cancelled_completed_confirmed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_variant_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_variant_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRequirementStatus(arg0: string, arg1: Variant_closed_assigned): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequirementStatus(arg0, to_candid_variant_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequirementStatus(arg0, to_candid_variant_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ConsultationBooking_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationBooking): ConsultationBooking {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LawyerProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LawyerProfile): Promise<LawyerProfile> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_LegalRequirement_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LegalRequirement): LegalRequirement {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LawyerProfile]): Promise<LawyerProfile | null> {
    return value.length === 0 ? null : await from_candid_LawyerProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    userId: Principal;
    yearsExperience: bigint;
    name: string;
    education: string;
    languages: Array<string>;
    averageRating: number;
    specialization: string;
    photo: [] | [_ExternalBlob];
    totalReviews: bigint;
    consultationFee: bigint;
    location: string;
    verificationStatus: {
        verified: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    };
    verificationDoc: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    userId: Principal;
    yearsExperience: bigint;
    name: string;
    education: string;
    languages: Array<string>;
    averageRating: number;
    specialization: string;
    photo?: ExternalBlob;
    totalReviews: bigint;
    consultationFee: bigint;
    location: string;
    verificationStatus: Variant_verified_pending_rejected;
    verificationDoc?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        userId: value.userId,
        yearsExperience: value.yearsExperience,
        name: value.name,
        education: value.education,
        languages: value.languages,
        averageRating: value.averageRating,
        specialization: value.specialization,
        photo: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.photo)),
        totalReviews: value.totalReviews,
        consultationFee: value.consultationFee,
        location: value.location,
        verificationStatus: from_candid_variant_n23(_uploadFile, _downloadFile, value.verificationStatus),
        verificationDoc: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.verificationDoc))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: {
        client: null;
    } | {
        lawyer: null;
    };
}): {
    name: string;
    role: Variant_client_lawyer;
} {
    return {
        name: value.name,
        role: from_candid_variant_n28(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        completed: null;
    } | {
        confirmed: null;
    };
    clientId: Principal;
    requirementId: [] | [string];
    scheduledDate: _Time;
    lawyerId: Principal;
    notes: string;
}): {
    id: string;
    status: Variant_cancelled_pending_completed_confirmed;
    clientId: Principal;
    requirementId?: string;
    scheduledDate: Time;
    lawyerId: Principal;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n35(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        requirementId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.requirementId)),
        scheduledDate: value.scheduledDate,
        lawyerId: value.lawyerId,
        notes: value.notes
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        closed: null;
    } | {
        assigned: null;
    } | {
        open: null;
    };
    title: string;
    clientId: Principal;
    createdAt: _Time;
    description: string;
    legalCategory: string;
    location: string;
}): {
    id: string;
    status: Variant_closed_assigned_open;
    title: string;
    clientId: Principal;
    createdAt: Time;
    description: string;
    legalCategory: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n40(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        createdAt: value.createdAt,
        description: value.description,
        legalCategory: value.legalCategory,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): Variant_verified_pending_rejected {
    return "verified" in value ? Variant_verified_pending_rejected.verified : "pending" in value ? Variant_verified_pending_rejected.pending : "rejected" in value ? Variant_verified_pending_rejected.rejected : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    lawyer: null;
}): Variant_client_lawyer {
    return "client" in value ? Variant_client_lawyer.client : "lawyer" in value ? Variant_client_lawyer.lawyer : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): Variant_cancelled_pending_completed_confirmed {
    return "cancelled" in value ? Variant_cancelled_pending_completed_confirmed.cancelled : "pending" in value ? Variant_cancelled_pending_completed_confirmed.pending : "completed" in value ? Variant_cancelled_pending_completed_confirmed.completed : "confirmed" in value ? Variant_cancelled_pending_completed_confirmed.confirmed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    assigned: null;
} | {
    open: null;
}): Variant_closed_assigned_open {
    return "closed" in value ? Variant_closed_assigned_open.closed : "assigned" in value ? Variant_closed_assigned_open.assigned : "open" in value ? Variant_closed_assigned_open.open : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LawyerProfile>): Promise<Array<LawyerProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LawyerProfile_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConsultationBooking>): Array<ConsultationBooking> {
    return value.map((x)=>from_candid_ConsultationBooking_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LegalRequirement>): Array<LegalRequirement> {
    return value.map((x)=>from_candid_LegalRequirement_n38(_uploadFile, _downloadFile, x));
}
function to_candid_ConsultationBooking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationBooking): _ConsultationBooking {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_LawyerProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LawyerProfile): Promise<_LawyerProfile> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_LegalRequirement_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LegalRequirement): _LegalRequirement {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_cancelled_pending_completed_confirmed;
    clientId: Principal;
    requirementId?: string;
    scheduledDate: Time;
    lawyerId: Principal;
    notes: string;
}): {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        completed: null;
    } | {
        confirmed: null;
    };
    clientId: Principal;
    requirementId: [] | [string];
    scheduledDate: _Time;
    lawyerId: Principal;
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        requirementId: value.requirementId ? candid_some(value.requirementId) : candid_none(),
        scheduledDate: value.scheduledDate,
        lawyerId: value.lawyerId,
        notes: value.notes
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    userId: Principal;
    yearsExperience: bigint;
    name: string;
    education: string;
    languages: Array<string>;
    averageRating: number;
    specialization: string;
    photo?: ExternalBlob;
    totalReviews: bigint;
    consultationFee: bigint;
    location: string;
    verificationStatus: Variant_verified_pending_rejected;
    verificationDoc?: ExternalBlob;
}): Promise<{
    bio: string;
    userId: Principal;
    yearsExperience: bigint;
    name: string;
    education: string;
    languages: Array<string>;
    averageRating: number;
    specialization: string;
    photo: [] | [_ExternalBlob];
    totalReviews: bigint;
    consultationFee: bigint;
    location: string;
    verificationStatus: {
        verified: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    };
    verificationDoc: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        userId: value.userId,
        yearsExperience: value.yearsExperience,
        name: value.name,
        education: value.education,
        languages: value.languages,
        averageRating: value.averageRating,
        specialization: value.specialization,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        totalReviews: value.totalReviews,
        consultationFee: value.consultationFee,
        location: value.location,
        verificationStatus: to_candid_variant_n17(_uploadFile, _downloadFile, value.verificationStatus),
        verificationDoc: value.verificationDoc ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.verificationDoc)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_closed_assigned_open;
    title: string;
    clientId: Principal;
    createdAt: Time;
    description: string;
    legalCategory: string;
    location: string;
}): {
    id: string;
    status: {
        closed: null;
    } | {
        assigned: null;
    } | {
        open: null;
    };
    title: string;
    clientId: Principal;
    createdAt: _Time;
    description: string;
    legalCategory: string;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n43(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        createdAt: value.createdAt,
        description: value.description,
        legalCategory: value.legalCategory,
        location: value.location
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Variant_client_lawyer;
}): {
    name: string;
    role: {
        client: null;
    } | {
        lawyer: null;
    };
} {
    return {
        name: value.name,
        role: to_candid_variant_n46(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_completed_confirmed): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == Variant_cancelled_pending_completed_confirmed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_completed_confirmed.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_completed_confirmed.completed ? {
        completed: null
    } : value == Variant_cancelled_pending_completed_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_verified_pending_rejected): {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
} {
    return value == Variant_verified_pending_rejected.verified ? {
        verified: null
    } : value == Variant_verified_pending_rejected.pending ? {
        pending: null
    } : value == Variant_verified_pending_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_closed_assigned_open): {
    closed: null;
} | {
    assigned: null;
} | {
    open: null;
} {
    return value == Variant_closed_assigned_open.closed ? {
        closed: null
    } : value == Variant_closed_assigned_open.assigned ? {
        assigned: null
    } : value == Variant_closed_assigned_open.open ? {
        open: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_client_lawyer): {
    client: null;
} | {
    lawyer: null;
} {
    return value == Variant_client_lawyer.client ? {
        client: null
    } : value == Variant_client_lawyer.lawyer ? {
        lawyer: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_completed_confirmed): {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == Variant_cancelled_completed_confirmed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_completed_confirmed.completed ? {
        completed: null
    } : value == Variant_cancelled_completed_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_closed_assigned): {
    closed: null;
} | {
    assigned: null;
} {
    return value == Variant_closed_assigned.closed ? {
        closed: null
    } : value == Variant_closed_assigned.assigned ? {
        assigned: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_verified_rejected): {
    verified: null;
} | {
    rejected: null;
} {
    return value == Variant_verified_rejected.verified ? {
        verified: null
    } : value == Variant_verified_rejected.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
